CREATE TABLE `tableName` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `gamesn` bigint(20) DEFAULT NULL COMMENT '房间流水号',
  `username` varchar(190) DEFAULT NULL COMMENT '玩家账号',
  `room_id` int(11) DEFAULT NULL COMMENT '房间ID',
  `room_type` int(11) DEFAULT NULL COMMENT '房间类型',
  `game_id` int(11) DEFAULT NULL COMMENT '游戏ID',
  `table_Id` int(11) DEFAULT NULL COMMENT '桌号ID',
  `pos_id` int(11) DEFAULT NULL COMMENT '座位号',
  `banker` int(11) DEFAULT NULL COMMENT '庄家的座位号',
  `number` int(11) DEFAULT NULL COMMENT '玩家人数',
  `cart` varchar(10000) DEFAULT NULL COMMENT '玩家手牌',
  `valid_bet` bigint(20) DEFAULT NULL COMMENT '有效投注',
  `all_bet` bigint(20) DEFAULT NULL COMMENT '总投注',
  `profit` bigint(20) DEFAULT NULL COMMENT '利润(输、赢)',
  `current_score` bigint(20) DEFAULT NULL COMMENT '玩家身上剩余分数',
  `take_score` bigint(20) DEFAULT NULL COMMENT '玩家携带金额',
  `deduct` int(11) DEFAULT NULL COMMENT '抽水',
  `start_time` datetime DEFAULT NULL COMMENT '游戏开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '游戏结束时间',
  `platform` int(11) DEFAULT NULL COMMENT '平台id',
  `agent` varchar(50) DEFAULT NULL COMMENT '代理',
  `game_no` varchar(50) DEFAULT NULL COMMENT '牌局编号',
  `data` text,
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `index_gameendtime_channel` (`end_time`,`platform`) USING BTREE,
  KEY `index_gameendtime` (`end_time`) USING BTREE,
  KEY `index_gameendtime_account` (`end_time`,`username`) USING BTREE,
  KEY `index_gameendtime_kindId` (`end_time`,`game_id`) USING BTREE,
  KEY `index_gameendtime_kindId_serverId` (`end_time`,`game_id`,`room_id`) USING BTREE,
  KEY `index_accounts` (`username`),
  KEY `index_gamestarttime_account` (`start_time`,`username`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
